services:
  myllm:
    build: ./myLLM/.
    restart: unless-stopped
    container_name: myllm
    working_dir: /app
    ports:
      - "8000:8000"
    # you can set a lot of parameters. A brief description of the parameters we use here:
    # -- model: the model we want to use. In this case it is 'NousResearch/Meta-Llama-3-8B-Instruct'
    # -- swap-space: the amount of swap space to use. In this case it is 2Gb
    # -- dtype: the data type to use. In this case it is 'half'
    # -- max-model-length: the maximum length of the model. In this case it is 2048
    # -- api-key: the API key that will be needed to make requests. In this case it is 'my-unique-api-key'
    command: "vllm serve --model NousResearch/Meta-Llama-3-8B-Instruct --swap-space 2.0 --dtype=half --max-model-length 2048 --api-key my-unique-api-key"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]  # This requests GPU support for the container
          memory: 4g
    # Optional environment variables (for CUDA, etc.)
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible to the container
      - HUGGING_FACE_HUB_TOKEN=<your HuggingFace token> # if you want to use a model, that requires a HuggingFace account, you need to set your access token here